const gamColors = {
  'error-container': '#93000a',
  'primary-fixed-dim': '#00dbe9',
  'on-tertiary-fixed': '#1c1b1b',
  'on-error-container': '#ffdad6',
  'surface-container-low': '#0d1c2d',
  'on-secondary-fixed': '#320047',
  outline: '#849495',
  'primary-fixed': '#7df4ff',
  'surface-dim': '#051424',
  'on-primary': '#00363a',
  'on-background': '#d4e4fa',
  'tertiary-container': '#dcd9d8',
  'surface-container-high': '#1c2b3c',
  background: '#051424',
  'surface-variant': '#273647',
  tertiary: '#f9f5f5',
  primary: '#dbfcff',
  'surface-container-highest': '#273647',
  'outline-variant': '#3b494b',
  'inverse-surface': '#d4e4fa',
  'inverse-primary': '#006970',
  secondary: '#ecb2ff',
  'on-surface-variant': '#b9cacb',
  'on-secondary': '#520071',
  'secondary-fixed': '#f8d8ff',
  'on-surface': '#d4e4fa',
  'on-primary-container': '#006970',
  'secondary-container': '#cf5cff',
  'surface-container': '#122131',
  'on-tertiary-container': '#605f5e',
  'on-tertiary-fixed-variant': '#474646',
  'primary-container': '#00f0ff',
  surface: '#051424',
  'tertiary-fixed-dim': '#c8c6c5',
  'on-primary-fixed': '#002022',
  'on-primary-fixed-variant': '#004f54',
  'secondary-fixed-dim': '#ecb2ff',
  'on-secondary-fixed-variant': '#74009f',
  'tertiary-fixed': '#e5e2e1',
  error: '#ffb4ab',
  'on-secondary-container': '#480063',
  'surface-bright': '#2c3a4c',
  'surface-tint': '#00dbe9',
  'surface-container-lowest': '#010f1f',
  'inverse-on-surface': '#233143',
  'on-error': '#690005',
  'on-tertiary': '#313030',
};

const config = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: gamColors,
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        margin: '24px',
        lg: '24px',
        '2xl': '48px',
        gutter: '20px',
        xl: '32px',
        xs: '4px',
        sm: '8px',
        md: '16px',
        '3xl': '64px',
        unit: '4px',
      },
      fontFamily: {
        inter: ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'mono-data': ['monospace'],
        'body-md': ['Inter', 'sans-serif'],
        h1: ['Inter', 'sans-serif'],
        h2: ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        h3: ['Inter', 'sans-serif'],
        'label-caps': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-sm': ['14px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
        'mono-data': ['14px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        h1: ['40px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        h2: ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        h3: ['24px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-caps': ['12px', { lineHeight: '1.2', letterSpacing: '0.08em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
};

export default config;
