[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info
    Parsers_File /fluent-bit/etc/parsers.conf

[INPUT]
    Name              forward
    Listen            0.0.0.0
    Port              24224

[FILTER]
    Name              modify
    Match             *
    Add               env local-prod-like
    Add               cluster local-gam-trade

[OUTPUT]
    Name              loki
    Match             user-api
    Host              loki
    Port              3100
    Labels            service=user-api,env=$env,cluster=$cluster
    Label_Keys        level
    Line_Format       json
    Auto_Kubernetes_Labels Off

[OUTPUT]
    Name              loki
    Match             cms-api
    Host              loki
    Port              3100
    Labels            service=cms-api,env=$env,cluster=$cluster
    Label_Keys        level
    Line_Format       json
    Auto_Kubernetes_Labels Off

[OUTPUT]
    Name              loki
    Match             order-worker
    Host              loki
    Port              3100
    Labels            service=order-worker,env=$env,cluster=$cluster
    Label_Keys        level
    Line_Format       json
    Auto_Kubernetes_Labels Off

[OUTPUT]
    Name              loki
    Match             payment-worker
    Host              loki
    Port              3100
    Labels            service=payment-worker,env=$env,cluster=$cluster
    Label_Keys        level
    Line_Format       json
    Auto_Kubernetes_Labels Off

[OUTPUT]
    Name              loki
    Match             notification-worker
    Host              loki
    Port              3100
    Labels            service=notification-worker,env=$env,cluster=$cluster
    Label_Keys        level
    Line_Format       json
    Auto_Kubernetes_Labels Off

[OUTPUT]
    Name              loki
    Match             user-web
    Host              loki
    Port              3100
    Labels            service=user-web,env=$env,cluster=$cluster
    Line_Format       json
    Auto_Kubernetes_Labels Off

[OUTPUT]
    Name              loki
    Match             admin-web
    Host              loki
    Port              3100
    Labels            service=admin-web,env=$env,cluster=$cluster
    Line_Format       json
    Auto_Kubernetes_Labels Off

[OUTPUT]
    Name              loki
    Match             user-app
    Host              loki
    Port              3100
    Labels            service=user-app,env=$env,cluster=$cluster
    Line_Format       json
    Auto_Kubernetes_Labels Off
