# Lints and warnings
caps-lints = ["warn", "arising"]
doc-lints = ["warn", "arising"]
style = ["warn", "arising"]
pedantic = "warn"
clogic = "warn"
complexity = "warn"
perf = "warn"
unused = "warn"
restrict-glob = "warn"

# Allow these lints
allow = [
    "dead_code",
    "unused_variables",
    "unused_imports",
]

# Disallow these lints
disallow = []

# Warn on these
warn = [
    "bad_style",
    "deprecated",
    "drop_bounds",
    "drop_ref_tracking",
    "elided_lifetimes_in_paths",
    "explicit_outlives_requirements",
    "invalid_html",
    "keyword_idents",
    "let_underscore",
    "macro_use_extern_crate",
    "meta_variable_mismatch",
    "missing_copy_implementations",
    "missing_docs",
    "missing_debug_implementations",
    "non_ascii_idents",
    "no_mangle_generic_items",
    "non_snake_case",
    "non_upper_case_globals",
    "noop_method_clash",
    "path_statements",
    "private_doc_tests",
    "semicolon_in_expressions_from_macros",
    "stable_features",
    "temporary_borrowing",
    "trivial_numeric_casts",
    "unfulfilled_lint_expectations",
    "unnameable_types",
    "unreachable_pub",
    "unsafe_code",
    "unsafe_op_in_unsafe_fn",
    "unused_qualifications",
    "unused_results",
    "variant_size_differences",
]